### ISSUE TITLE
Pods in the same stack should (optionally) run on the same node

### ISSUE THREAD

**Issue by craig-willis** [nds-org/ndslabs#277]
The CHEESE arpspoof case requires that hacker, victim and server all be collocated on the same node. We should be able to achieve this with the current NDSLabs pod-centric design by pod affinity.

The following example demonstrates how to use labels to ensure that pods run on the same node:
https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#more-practical-use-cases

We should also include a spec-level configuration option to enable -- and should be disabled by default.

**Comment by bodom0015** [comment]
Since it helps me to enumerate things, here are the pieces I am seeing to this:
1. (optional, short-term) Update Helm chart to allow user to set default `affinity` for all services
2. (required, short-term) Update API server to accept a new spec parameter `affinity` and pass it directly through verbatim to the Kubernetes spec
3. (very optional, long term) Update UI to expose new spec field `affinity`
4. Update Swagger spec and documentation to reflect and describe new spec field

In both cases, `affinity` could specify either affinity or anti-affinity for pods and would be passed through directly to Kubernetes. This is obviously an advanced feature that could break a few thing if the user doesn't specify affinity correctly, so it may take some time to think about how a sensible UI for making such selection.

I also need to familiarize myself a bit more with the available options on Kubernetes Pod `spec.affinity`.

**Comment by bodom0015** [comment]
Appears to have been fixed by #285
